# Generated by Django 4.1.12 on 2023-11-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('sreg', models.IntegerField()),
                ('sphn', models.IntegerField()),
                ('saddress', models.CharField(max_length=300)),
                ('semail', models.EmailField(max_length=254)),
                ('admndate', models.DateField()),
                ('stc', models.CharField(max_length=200)),
                ('sfather', models.CharField(max_length=200)),
                ('smother', models.CharField(max_length=200)),
                ('sfphn', models.IntegerField()),
                ('sfoccupation', models.CharField(max_length=200)),
                ('sfincome', models.CharField(max_length=200)),
                ('sdob', models.CharField(max_length=15)),
                ('saadhar', models.IntegerField()),
                ('sbld', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('tid', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
