# Generated by Django 4.1.12 on 2023-11-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminsss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('sreg', models.IntegerField()),
                ('sphn', models.IntegerField()),
                ('scourse', models.CharField(max_length=200)),
                ('saddress', models.CharField(max_length=300)),
                ('semail', models.EmailField(max_length=254)),
                ('admndate', models.DateField()),
                ('stc', models.CharField(max_length=200)),
                ('sfather', models.CharField(max_length=200)),
                ('smother', models.CharField(max_length=200)),
                ('sfphn', models.IntegerField()),
                ('sfoccupation', models.CharField(max_length=200)),
                ('sfincome', models.CharField(max_length=200)),
                ('sdob', models.CharField(max_length=15)),
                ('saadhar', models.IntegerField()),
                ('sbld', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'adminn',
            },
        ),
        migrations.CreateModel(
            name='Tadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=200)),
                ('teacherid', models.IntegerField()),
                ('trating', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_teacher',
            },
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
