# Generated by Django 4.1.12 on 2023-11-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0002_adminsss_tadmin_delete_admins'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminsss',
            table='adminn',
        ),
    ]
