# Generated by Django 4.1.12 on 2023-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0003_alter_adminsss_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadmin',
            name='trating',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
