# Generated by Django 4.1.12 on 2023-11-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0004_alter_tadmin_trating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tadmin',
            name='trating',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20),
        ),
    ]
