# Generated by Django 4.1.12 on 2023-11-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0006_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsss',
            name='saadhar',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='adminsss',
            name='sfphn',
            field=models.PositiveBigIntegerField(),
        ),
    ]
