# Generated by Django 4.1.12 on 2023-11-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0007_alter_adminsss_saadhar_alter_adminsss_sfphn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence_percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_sub1', models.FloatField()),
                ('p_sub2', models.FloatField()),
                ('p_sub3', models.FloatField()),
                ('p_sub4', models.FloatField()),
                ('p_sub5', models.FloatField()),
                ('p_sub6', models.FloatField()),
                ('p_sub7', models.FloatField()),
                ('p_sub8', models.FloatField()),
            ],
            options={
                'db_table': 'attendence_percentage',
            },
        ),
    ]
