# Generated by Django 4.1.12 on 2023-11-25 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0009_delete_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence_percentage',
        ),
    ]
