# Generated by Django 4.1.12 on 2023-11-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0011_attendence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
