# Generated by Django 4.1.12 on 2023-11-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0013_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='p1',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p2',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p3',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p4',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p5',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p6',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p7',
            field=models.IntegerField(default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p8',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
