# Generated by Django 4.1.12 on 2023-11-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0014_alter_attendence_p1_alter_attendence_p2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
