# Generated by Django 4.1.12 on 2023-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0015_delete_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('sreg', models.IntegerField()),
                ('p1', models.CharField(default=0, max_length=17)),
                ('p2', models.CharField(default=0, max_length=17)),
                ('p3', models.CharField(default=0, max_length=17)),
                ('p4', models.CharField(default=0, max_length=17)),
                ('p5', models.CharField(default=0, max_length=17)),
                ('p6', models.CharField(default=0, max_length=17)),
                ('p7', models.CharField(default=0, max_length=15)),
                ('p8', models.CharField(default=0, max_length=15)),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
