# Generated by Django 4.1.12 on 2023-11-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0016_attendence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='p1',
            field=models.CharField(default='100', max_length=17),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p2',
            field=models.CharField(default='100', max_length=17),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p3',
            field=models.CharField(default='100', max_length=17),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p4',
            field=models.CharField(default='100', max_length=17),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p5',
            field=models.CharField(default='100', max_length=17),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p6',
            field=models.CharField(default='100', max_length=17),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p7',
            field=models.CharField(default='100', max_length=15),
        ),
        migrations.AlterField(
            model_name='attendence',
            name='p8',
            field=models.CharField(default='100', max_length=15),
        ),
    ]
