# Generated by Django 4.1.12 on 2023-11-27 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0019_alter_attendence_p1_alter_attendence_p2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Adminsss',
        ),
        migrations.DeleteModel(
            name='Attendence',
        ),
        migrations.DeleteModel(
            name='Stu',
        ),
        migrations.DeleteModel(
            name='Tadmin',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
