# Generated by Django 4.1.12 on 2023-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clgapp', '0020_delete_adminsss_delete_attendence_delete_stu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminsss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('sreg', models.IntegerField()),
                ('sphn', models.IntegerField()),
                ('scourse', models.CharField(max_length=200)),
                ('saddress', models.CharField(max_length=300)),
                ('semail', models.EmailField(max_length=254)),
                ('admndate', models.DateField()),
                ('stc', models.CharField(max_length=200)),
                ('sfather', models.CharField(max_length=200)),
                ('smother', models.CharField(max_length=200)),
                ('sfphn', models.PositiveBigIntegerField()),
                ('sfoccupation', models.CharField(max_length=200)),
                ('sfincome', models.CharField(max_length=200)),
                ('sdob', models.CharField(max_length=15)),
                ('saadhar', models.CharField(max_length=16)),
                ('sbld', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'adminn',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=200)),
                ('sreg', models.IntegerField()),
                ('p1', models.CharField(default='100', max_length=7)),
                ('p2', models.CharField(default='100', max_length=7)),
                ('p3', models.CharField(default='100', max_length=7)),
                ('p4', models.CharField(default='100', max_length=7)),
                ('p5', models.CharField(default='100', max_length=7)),
                ('p6', models.CharField(default='100', max_length=7)),
                ('p7', models.CharField(default='100', max_length=7)),
                ('p8', models.CharField(default='100', max_length=7)),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
        migrations.CreateModel(
            name='Stu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Tadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachername', models.CharField(max_length=200)),
                ('teacherid', models.IntegerField()),
                ('trating', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
            ],
            options={
                'db_table': 'admin_teacher',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=200)),
                ('tid', models.IntegerField()),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
